  name: RandomEnchant
  main: xenialdan\RandomEnchant\Loader
  version: 1.0.2
  api: ['*', '3.0.0-ALPHA2', '3.0.0-ALPHA1', '3.0.0']
  load: POSTWORLD
  authors: [XenialDan]
  prefix: "RandomEnchant by XenialDan"
  permissions:
    randomenchant:
      description: Perm for getting enchants
      default: op